import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Toaster } from "sonner";
import NavbarWrapper from "@/components/NavbarWrapper";
import { cookies } from "next/headers";
import Footer from "@/components/Footer";
import { Box } from "@mui/material";
import { UserProvider } from "@/context/UserContext";
import User from "@/models/User";
import connectDB from "@/lib/mongodb";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
   const cookiesStore = await cookies()
   //console.log("Cookies in layout:", cookiesStore.getAll());
    const token = cookiesStore.get("token")?.value;
    const name = cookiesStore.get("name")?.value;
    const id = cookiesStore.get("id")?.value;
    
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}  style={{ margin: 0 }}>
        <Box
          sx={{
            minHeight: "100vh",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <Box sx={{ flex: 1 }}>
            <UserProvider 
            //value={{ token: null, name: null, id: null, email: null, role: null }}
            value={{ token, name, id, email:null, role:null}}
            >
           <NavbarWrapper 
           //token={token} name={name}
            />
            <Toaster richColors position="top-right" />
            {children }
            </UserProvider>
              </Box>
          <Footer />
        </Box>
      </body>
    </html>
  );
}
